spring.datasource.url=${MINDFUL_FINANCE_DB_URL:jdbc:postgresql://localhost:55432/mindfulfinance}
spring.datasource.username=${MINDFUL_FINANCE_DB_USERNAME:mindfulfinance}
spring.datasource.password=${MINDFUL_FINANCE_DB_PASSWORD:mindfulfinance}
